version: '3.8'
services:
  cache:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel debug
    volumes:
      - cache:/data
  api:
    container_name: hamppred-api
    build:
      context: ./
    image: hamppred-api
    depends_on:
      - cache
    ports:
      - 8080:8080
    environment:
      REDIS_HOST: cache
      REDIS_PORT: 6379
      REDIS_PASSWORD: eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    links:
      - cache
    volumes:
      - ./hamp_pred:/hamp_pred
volumes:
  cache:
    driver: local