FROM python:3.9.12-bullseye as base

WORKDIR /


COPY requirements.txt requirements.txt
RUN pip install -r requirements.txt
RUN pip install Redis
COPY hamp_pred hamp_pred
COPY external external
COPY celery-entry.sh celery-entry.sh
COPY data data
ENTRYPOINT ["/bin/sh", "/celery-entry.sh"]